// GENERATED by scripts/generate-exclusions.py from packages/domain/lib/exclusion.dart.
// Do not edit. Edit the Dart and re-run the generator; ./scripts/verify.sh fails on drift.
//
// ONE VOCABULARY, TWO LANGUAGES. `discover` parses a Customer's phrase server-side and the Customer
// web surface will need the same words. A second hand-maintained copy drifts, and the direction it
// drifts is an allergy recognised on one surface and not the other.
//
// The Dart file is the source because that is where it is reviewed — localization-reviewer found
// three critical bugs in it on 2026-08-07, including a plainly stated nut allergy that returned
// "nothing excluded".

export interface Exclusion {
  readonly id: string;
  readonly surfaceForms: readonly string[];
}

/// Longest first. `من غير ما يكون فيه` contains `من غير`, and matching the shorter one first takes
/// the rest of the phrase as the food.
export const NEGATION_MARKERS: readonly string[] = [
  'عندي حساسية من',
  'عندى حساسية من',
  'حساسية من',
  'من غير ما يكون فيه',
  'مش عايزة',
  'مش عاوزة',
  'مش عايز',
  'مش عاوز',
  'من غير',
  'بدون',
  'بلاش',
];

/// Words that can sit between the marker and the food without being part of it.
export const FILLERS: readonly string[] = [
  'أي',
  'اي',
  'ولا',
  'شوية',
];

export const EXCLUSIONS: readonly Exclusion[] = [
  {
    id: 'meat',
    surfaceForms: [
      'لحمة',
      'لحمه',
      'لحم',
      'لحوم',
      'كبدة',
      'كبده',
      'سجق',
      'بسطرمة',
      'لانشون',
    ],
  },
  {
    id: 'chicken',
    surfaceForms: [
      'فراخ',
      'فرخة',
      'فرخه',
      'فرخ',
      'دجاج',
      'بانيه',
      'بانية',
    ],
  },
  {
    id: 'fish',
    surfaceForms: [
      'سمك',
      'سمكة',
      'سمكه',
      'أسماك',
      'اسماك',
      'سلمون',
      'رنجة',
      'رنجه',
      'فسيخ',
      'بلطي',
      'بلطى',
      'بوري',
      'بورى',
      'سردين',
    ],
  },
  {
    id: 'shellfish',
    surfaceForms: [
      'جمبري',
      'جمبرى',
      'استاكوزا',
      'إستاكوزا',
      'أستاكوزا',
      'كابوريا',
      'محار',
      'سبيط',
      'كاليماري',
      'جندوفلي',
    ],
  },
  {
    id: 'egg',
    surfaceForms: [
      'بيض',
      'بيضة',
      'بيضه',
    ],
  },
  {
    id: 'dairy',
    surfaceForms: [
      'لبن',
      'حليب',
      'جبن',
      'جبنة',
      'جبنه',
      'زبادي',
      'زبادى',
      'قشطة',
      'قشطه',
      'قشدة',
      'زبدة',
      'زبده',
      'سمنة',
      'سمنه',
      'كريمة',
      'كريمه',
      'قريش',
    ],
  },
  {
    id: 'peanut',
    surfaceForms: [
      'فول سوداني',
      'فول سودانى',
      'سوداني',
      'سودانى',
    ],
  },
  {
    id: 'nuts',
    surfaceForms: [
      'مكسرات',
      'لوز',
      'عين جمل',
      'عين الجمل',
      'بندق',
      'فستق',
      'كاجو',
      'صنوبر',
      'بيكان',
    ],
  },
  {
    id: 'sesame',
    surfaceForms: [
      'سمسم',
      'طحينة',
      'طحينه',
    ],
  },
  {
    id: 'gluten',
    surfaceForms: [
      'قمح',
      'دقيق',
      'جلوتين',
      'غلوتين',
      'سميد',
      'بقسماط',
      'مكرونة',
      'عيش',
      'خبز',
      'رقاق',
      'فريك',
      'شعرية',
      'عجينة',
      'شوفان',
    ],
  },
  {
    id: 'onion',
    surfaceForms: [
      'بصل',
    ],
  },
  {
    id: 'garlic',
    surfaceForms: [
      'توم',
      'ثوم',
    ],
  },
];
