// GENERATED by scripts/generate-exclusions.py from packages/domain/lib/exclusion.dart.
// Do not edit. Edit the Dart and re-run the generator; ./scripts/verify.sh fails on drift.
//
// ONE VOCABULARY, TWO LANGUAGES. `discover` parses a Customer's phrase server-side and the Customer
// web surface will need the same words. A second hand-maintained copy drifts, and the direction it
// drifts is an allergy recognised on one surface and not the other.
//
// The Dart file is the source because that is where it is reviewed — localization-reviewer found
// three critical bugs in it on 2026-08-07, including a plainly stated nut allergy that returned
// "nothing excluded".

export interface Exclusion {
  readonly id: string;
  readonly surfaceForms: readonly string[];
}

/// Longest first. `من غير ما يكون فيه` contains `من غير`, and matching the shorter one first takes
/// the rest of the phrase as the food.
export const NEGATION_MARKERS: readonly string[] = [
  'عندي حساسية من',
  'حساسية من',
  'من غير ما يكون فيه',
  'مش عايزة',
  'مش عاوزة',
  'مش عايز',
  'مش عاوز',
  'من غير',
  'بدون',
  'بلاش',
  'مباكلش',
  'مبكلش',
];

/// Words that can sit between the marker and the food without being part of it.
export const FILLERS: readonly string[] = [
  'اي',
  'شويه',
];

export const EXCLUSIONS: readonly Exclusion[] = [
  {
    id: 'meat',
    surfaceForms: [
      'لحم',
      'لحوم',
      'كبد',
      'سجق',
      'بسطرمة',
      'لانشون',
    ],
  },
  {
    id: 'chicken',
    surfaceForms: [
      'فراخ',
      'فرخ',
      'دجاج',
      'بانيه',
    ],
  },
  {
    id: 'fish',
    surfaceForms: [
      'سمك',
      'أسماك',
      'سلمون',
      'رنجة',
      'فسيخ',
      'بلطي',
      'بوري',
      'سردين',
      'تونة',
    ],
  },
  {
    id: 'shellfish',
    surfaceForms: [
      'جمبري',
      'استاكوزا',
      'كابوريا',
      'محار',
      'سبيط',
      'كاليماري',
      'قريدس',
      'حبار',
      'جندوفلي',
    ],
  },
  {
    id: 'egg',
    surfaceForms: [
      'بيض',
      'مايونيز',
    ],
  },
  {
    id: 'dairy',
    surfaceForms: [
      'لبن',
      'حليب',
      'جبن',
      'زبادي',
      'قشطة',
      'قشدة',
      'زبدة',
      'سمن',
      'كريمة',
      'قريش',
    ],
  },
  {
    id: 'peanut',
    surfaceForms: [
      'سوداني',
    ],
  },
  {
    id: 'nuts',
    surfaceForms: [
      'مكسرات',
      'لوز',
      'عين جمل',
      'عين الجمل',
      'بندق',
      'فستق',
      'كاجو',
      'صنوبر',
      'بيكان',
    ],
  },
  {
    id: 'sesame',
    surfaceForms: [
      'سمسم',
      'طحينة',
    ],
  },
  {
    id: 'gluten',
    surfaceForms: [
      'قمح',
      'دقيق',
      'جلوتين',
      'غلوتين',
      'سميد',
      'بقسماط',
      'مكرونة',
      'معكرونة',
      'عيش',
      'خبز',
      'رقاق',
      'فريك',
      'شعرية',
      'عجين',
      'شوفان',
    ],
  },
  {
    id: 'onion',
    surfaceForms: [
      'بصل',
    ],
  },
  {
    id: 'garlic',
    surfaceForms: [
      'توم',
      'ثوم',
    ],
  },
];
