#!/usr/bin/env python3
"""Compile the exclusion vocabulary from Dart into TypeScript, so there is one of it.

WHY THIS EXISTS. `discover` parses a Customer's phrase server-side — the Edge Function needs the
negation markers and the food list, and so will the Customer web surface. The vocabulary already
lives in `packages/domain/lib/exclusion.dart`, where localization-reviewer read it and found three
critical bugs. A second hand-maintained copy in TypeScript would drift, and the direction it drifts
is a Customer's allergy going unrecognised on one surface and not the other.

Same shape as `scripts/generate-prompts.ts`: one source, one generated file, committed, and a gate
check that fails on drift. Edit the Dart and re-run this — never the generated file.

    python3 scripts/generate-exclusions.py            # write
    python3 scripts/generate-exclusions.py --check    # fail if the committed file is stale
"""

from __future__ import annotations

import pathlib
import re
import sys

SOURCE = pathlib.Path("packages/domain/lib/exclusion.dart")
TARGET = pathlib.Path("supabase/functions/_shared/exclusions.ts")

MARKERS_BLOCK = re.compile(
    r"static const List<String> negationMarkers = <String>\[(.*?)\];", re.DOTALL
)
FILLERS_BLOCK = re.compile(r"static const Set<String> _fillers = \{(.*?)\};", re.DOTALL)
ALL_BLOCK = re.compile(r"static const List<Exclusion> all = <Exclusion>\[(.*?)\n  \];", re.DOTALL)
ENTRY = re.compile(
    r"Exclusion\(\s*id:\s*'([^']+)',\s*surfaceForms:\s*\{(.*?)\},?\s*\)", re.DOTALL
)
QUOTED = re.compile(r"'([^']*)'")


def strip_comments(text: str) -> str:
    return re.sub(r"^\s*(//|///).*$", "", text, flags=re.MULTILINE)


def parse() -> tuple[list[str], list[str], list[tuple[str, list[str]]]]:
    dart = strip_comments(SOURCE.read_text(encoding="utf-8"))

    markers_match = MARKERS_BLOCK.search(dart)
    fillers_match = FILLERS_BLOCK.search(dart)
    all_match = ALL_BLOCK.search(dart)
    if not (markers_match and fillers_match and all_match):
        raise SystemExit(
            f"{SOURCE} no longer has the shape this generator reads. Fix the generator rather than "
            f"hand-writing {TARGET} — a hand-written copy is the thing this exists to prevent."
        )

    markers = QUOTED.findall(markers_match.group(1))
    fillers = QUOTED.findall(fillers_match.group(1))

    exclusions: list[tuple[str, list[str]]] = []
    for entry_id, forms in ENTRY.findall(all_match.group(1)):
        exclusions.append((entry_id, QUOTED.findall(forms)))

    if not markers or not exclusions:
        raise SystemExit("parsed an empty vocabulary — refusing to write it")
    return markers, fillers, exclusions


def render(markers: list[str], fillers: list[str], exclusions: list[tuple[str, list[str]]]) -> str:
    def arr(values: list[str], indent: str) -> str:
        return "\n".join(f"{indent}'{v}'," for v in values)

    entries = "\n".join(
        f"  {{\n    id: '{eid}',\n    surfaceForms: [\n"
        + arr(forms, "      ")
        + "\n    ],\n  },"
        for eid, forms in exclusions
    )

    return f"""// GENERATED by scripts/generate-exclusions.py from packages/domain/lib/exclusion.dart.
// Do not edit. Edit the Dart and re-run the generator; ./scripts/verify.sh fails on drift.
//
// ONE VOCABULARY, TWO LANGUAGES. `discover` parses a Customer's phrase server-side and the Customer
// web surface will need the same words. A second hand-maintained copy drifts, and the direction it
// drifts is an allergy recognised on one surface and not the other.
//
// The Dart file is the source because that is where it is reviewed — localization-reviewer found
// three critical bugs in it on 2026-08-07, including a plainly stated nut allergy that returned
// "nothing excluded".

export interface Exclusion {{
  readonly id: string;
  readonly surfaceForms: readonly string[];
}}

/// Longest first. `من غير ما يكون فيه` contains `من غير`, and matching the shorter one first takes
/// the rest of the phrase as the food.
export const NEGATION_MARKERS: readonly string[] = [
{arr(markers, "  ")}
];

/// Words that can sit between the marker and the food without being part of it.
export const FILLERS: readonly string[] = [
{arr(fillers, "  ")}
];

export const EXCLUSIONS: readonly Exclusion[] = [
{entries}
];
"""


def main() -> int:
    markers, fillers, exclusions = parse()
    rendered = render(markers, fillers, exclusions)

    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"   {TARGET} is stale — re-run python3 scripts/generate-exclusions.py")
            print("   An exclusion edit that was not regenerated is a surface that does not know")
            print("   about a food a Customer asked to avoid.")
            return 1
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}: {len(exclusions)} exclusions, {len(markers)} markers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
