#!/usr/bin/env python3
"""Compile the shared Arabic folding cases into a pgTAP suite, so all three folds answer to one file.

WHY THIS EXISTS. `foldArabic` lives three times — in packages/domain/lib/exclusion.dart, in
supabase/functions/discover/parse.ts, and as `public.fold_arabic` in SQL. It has to, because the
Customer's word is recognised in Dart, parsed again in the Edge Function, and matched against a
Cook's ingredient inside a Postgres predicate. Three implementations of one rule is the arrangement,
and the arrangement's failure mode is silent: a word recognised on one side that matches nothing on
the other.

On 2026-08-07 they disagreed on seventeen whitespace codepoints. Nothing noticed, because each side
had cases somebody had written for it and each side passed its own. Both reviewers found it by
building a throwaway differential harness. This is that harness, kept: one expectation file, and
three suites answering to it.

The Dart and TypeScript suites read the JSON directly. Postgres cannot, so its assertions are
generated here and the gate fails on drift — otherwise the SQL third could be edited by hand while
the other two moved, which is the exact shape of the problem.

    python3 scripts/generate-folding-cases.py            # write
    python3 scripts/generate-folding-cases.py --check    # fail if the committed file is stale
"""

from __future__ import annotations

import json
import pathlib
import sys

SOURCE = pathlib.Path("packages/domain/test/goldens/arabic_folding.json")
TARGET = pathlib.Path("supabase/tests/arabic_folding_test.sql")


def sql_literal(value: str) -> str:
    """A Postgres literal that survives every character in the case file.

    E'' with explicit \\uXXXX escapes rather than a plain quoted string, because the inputs are
    deliberately full of characters that are invisible in a source file — a zero-width joiner, a
    no-break space, a byte-order mark. Written literally, the next person to open the file would see
    a plain word and reasonably delete what looks like a duplicate case.
    """
    out = []
    for ch in value:
        point = ord(ch)
        if ch == "'":
            out.append("\\'")
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 < point < 0x7F:
            out.append(ch)
        elif point <= 0xFFFF:
            out.append(f"\\u{point:04X}")
        else:
            out.append(f"\\U{point:08X}")
    return "E'" + "".join(out) + "'"


def render(cases: list[dict]) -> str:
    lines = [
        "-- GENERATED by scripts/generate-folding-cases.py from",
        "-- packages/domain/test/goldens/arabic_folding.json. Do not edit.",
        "--",
        "-- Edit the JSON and re-run the generator; ./scripts/verify.sh fails on drift. The Dart and",
        "-- TypeScript folds answer to the same file in their own suites, which is the whole point:",
        "-- the three disagreed on seventeen whitespace codepoints on 2026-08-07 and every suite was",
        "-- green, because each side was checked against cases written for it alone.",
        "--",
        "-- EVERY INPUT IS WRITTEN AS ESCAPES. Many of these characters are invisible — a zero-width",
        "-- joiner, a no-break space, a byte-order mark — and written literally they would look like",
        "-- duplicate cases somebody should tidy away.",
        "",
        "BEGIN;",
        f"SELECT plan({len(cases) + 1});",
        "",
    ]

    for case in cases:
        lines.append(f"-- {case['id']}: {case['why']}")
        lines.append("SELECT is(")
        lines.append(f"  public.fold_arabic({sql_literal(case['input'])}),")
        lines.append(f"  {sql_literal(case['folded'])},")
        # The description is the CLAIM, not the failure. pgTAP prints it on a pass as well, and
        # "ok 1 - SQL disagrees with the shared expectation" reads as though the suite were
        # reporting the bug it exists to prevent.
        lines.append("  " + sql_literal(f"{case['id']}: {case['why']}"))
        lines.append(");")
        lines.append("")

    # Idempotence, asserted once over every case rather than per case: folding a folded word must
    # change nothing, or the three implementations diverge by how many times each applies a rule.
    idempotent = " UNION ALL ".join(
        f"SELECT public.fold_arabic(public.fold_arabic({sql_literal(c['input'])})) "
        f"<> public.fold_arabic({sql_literal(c['input'])}) AS moved"
        for c in cases
    )
    lines += [
        "-- Folding a folded word changes nothing.",
        "SELECT is(",
        f"  (SELECT count(*)::int FROM ({idempotent}) t WHERE moved),",
        "  0,",
        "  'folding is idempotent — a rule that keeps rewriting makes the three folds diverge by how "
        "many times each applies it'",
        ");",
        "",
        "SELECT * FROM finish();",
        "ROLLBACK;",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    if not SOURCE.exists():
        raise SystemExit(f"{SOURCE} is missing — it is the source of truth for the fold")

    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    cases = data.get("cases", [])
    if len(cases) < 25:
        raise SystemExit(
            f"only {len(cases)} folding case(s) — refusing to generate. The classes that actually "
            f"broke (tatweel, zero-width marks, non-ASCII spaces) need to stay covered."
        )

    rendered = render(cases)

    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"   {TARGET} has not been generated yet")
            return 1
        if TARGET.read_text(encoding="utf-8") != rendered:
            print(f"   {TARGET} is stale — run: python3 {__file__}")
            return 1
        print(f"   fold cases match ({len(cases)} case(s))")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}: {len(cases)} case(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
