#!/usr/bin/env python3
"""Compile the WHOLE exclusion vocabulary into a pgTAP sweep, so SC-005 is a claim about the set.

SC-005 says an excluded food appears ZERO times across the exclusion test set, and that one
occurrence is a failure of the feature rather than a ranking miss.

WHAT WAS ACTUALLY BEING CHECKED. `discovery_exclusion_test.sql` proves the predicate's behaviour on
a seven-Meal fixture that exercises four of the twelve exclusions. That suite is good and it is a
different claim: it tests HOW the predicate behaves — unknowns withheld, an empty array meaning
nothing, a literal % staying a character. It does not sweep the vocabulary, so "zero across the set"
rested on the entries somebody had written a case for.

THAT IS THE SHAPE OF EVERY BUG THIS FEATURE HAS HAD. The spelling gap was thirteen forms nobody had
checked one by one. The tatweel defeated all ninety-three at once. Both were found by walking the
whole list rather than the part somebody remembered. This walks the whole list.

For each exclusion it builds a Meal per surface form, in four spellings that a Cook actually
produces — as written, with ة written ه, with a tatweel inside, and with a no-break space if the
form has a space in it — and asserts that excluding that food returns NONE of them. Each is paired
with a control Meal that must survive, because a predicate that excluded everything would satisfy
every "did not appear" assertion here and be useless.

    python3 scripts/generate-exclusion-sweep.py            # write
    python3 scripts/generate-exclusion-sweep.py --check    # fail if the committed file is stale
"""

from __future__ import annotations

import pathlib
import re
import sys

SOURCE = pathlib.Path("packages/domain/lib/exclusion.dart")
TARGET = pathlib.Path("supabase/tests/discovery_exclusion_sweep_test.sql")

ALL_BLOCK = re.compile(r"static const List<Exclusion> all = <Exclusion>\[(.*?)\n  \];", re.DOTALL)
ENTRY = re.compile(r"Exclusion\(\s*id:\s*'([^']+)',\s*surfaceForms:\s*\{(.*?)\},?\s*\)", re.DOTALL)
QUOTED = re.compile(r"'([^']*)'")

TATWEEL = "ـ"
NBSP = " "


def strip_comments(text: str) -> str:
    return re.sub(r"^\s*(//|///).*$", "", text, flags=re.MULTILINE)


def spellings(form: str) -> list[tuple[str, str]]:
    """The ways a Cook writes `form`, each labelled with why it is here.

    Deliberately the classes that HAVE broken rather than every conceivable variant: a measurement
    that inflates itself cannot be used to decide anything, which is the lesson from the first pass
    at the spelling gap.
    """
    out = [(form, "as listed")]

    if "ة" in form:  # ة
        out.append((form.replace("ة", "ه"), "ة written ه"))

    if len(form) > 2:
        at = len(form) // 2
        out.append((form[:at] + TATWEEL + form[at:], "a stretched letter"))

    if " " in form:
        out.append((form.replace(" ", NBSP), "a no-break space between the words"))

    # Deduplicate while keeping order: a form with no ة and no space yields fewer spellings, and a
    # short one yields no tatweel case.
    seen: dict[str, str] = {}
    for text, why in out:
        seen.setdefault(text, why)
    return list(seen.items())


def sql_text_array(values: list[str]) -> str:
    return "ARRAY[" + ", ".join(escaped(v) for v in values) + "]"


def escaped(value: str) -> str:
    """A literal with every non-printable character written as an escape.

    The tatweel and the no-break space are invisible in a source file. Written literally, the next
    reader sees two identical-looking Meals and tidies one away — which is how a case that matters
    stops existing.
    """
    out = []
    for ch in value:
        point = ord(ch)
        if ch == "'":
            out.append("\\'")
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 < point < 0x7F:
            out.append(ch)
        elif point <= 0xFFFF:
            out.append(f"\\u{point:04X}")
        else:
            out.append(f"\\U{point:08X}")
    return "E'" + "".join(out) + "'"


def uuid_for(index: int) -> str:
    return f"'dddddddd-0000-4000-8000-{index:012d}'"


def render(exclusions: list[tuple[str, list[str]]]) -> str:
    header = f"""-- GENERATED by scripts/generate-exclusion-sweep.py from packages/domain/lib/exclusion.dart.
-- Do not edit. Add a food to the Dart vocabulary and re-run the generator; ./scripts/verify.sh
-- fails on drift.
--
-- SC-005 AS A CLAIM ABOUT THE SET, WHICH IS WHAT IT SAYS. An excluded food appears ZERO times, and
-- one occurrence is a failure of the feature rather than a ranking miss. discovery_exclusion_test
-- proves HOW the predicate behaves on a small fixture — unknowns withheld, an empty array meaning
-- nothing was excluded, a literal % staying a character. This sweeps every entry in the vocabulary,
-- because every bug this feature has had was in the entries nobody walked one by one: thirteen
-- spellings reached nothing, and a single tatweel defeated all ninety-three forms.
--
-- Each excluded food is planted in up to four spellings a Cook actually produces — as listed, with
-- ة written ه, with a stretched letter inside, and with a no-break space where the form has a space.
-- Every one is invisible or near-invisible on screen, which is why they are written as escapes here.
--
-- PAIRED WITH A CONTROL, always. A predicate that excluded everything would satisfy every
-- "did not appear" assertion in this file, so each exclusion also asserts that a Meal made of rice
-- and water survives it.

BEGIN;
SELECT plan({len(exclusions) * 2 + 2});

SELECT tests.create_supabase_user('cook@sweep.kafoo');

SELECT tests.authenticate_as('cook@sweep.kafoo');
INSERT INTO public.kitchen_profiles (cook_id, display_name, story, area, delivery_terms)
VALUES (tests.user_id('cook@sweep.kafoo'), 'مطبخ المسح', 'بطبخ من زمان', 'المهندسين', 'توصيل قريب');
SELECT tests.clear_authentication();

CREATE TEMP TABLE probe AS
SELECT (SELECT array_agg(0.1)::vector(768) FROM generate_series(1, 768)) AS v;
GRANT SELECT ON probe TO anon, authenticated;

-- One Meal per spelling of every form, plus one control that contains no excluded food at all.
INSERT INTO public.meals (id, cook_id, title, description, price, cuisine, category, status,
                          ingredients, allergens, embedding, published_at)
VALUES
"""

    rows: list[str] = []
    ids_by_exclusion: dict[str, list[str]] = {}
    index = 1

    # The control. Rice and water contain no listed food — asserted below rather than assumed.
    control_id = uuid_for(0)
    rows.append(
        f"  ({control_id}, tests.user_id('cook@sweep.kafoo'), 'أرز سادة', 'وصف', 25, "
        f"'مصري', 'رئيسي', 'published', ARRAY[E'\\u0623\\u0631\\u0632'], ARRAY[]::text[], "
        f"(SELECT array_agg(0.1)::vector(768) FROM generate_series(1, 768)), now())"
    )

    for eid, forms in exclusions:
        ids_by_exclusion[eid] = []
        for form in forms:
            for text, _why in spellings(form):
                row_id = uuid_for(index)
                ids_by_exclusion[eid].append(row_id)
                # The excluded text sits inside a longer ingredient, the way a Cook writes one.
                ingredient = escaped(text + " طازة")
                rows.append(
                    f"  ({row_id}, tests.user_id('cook@sweep.kafoo'), 'أكلة {index}', 'وصف', 50, "
                    f"'مصري', 'رئيسي', 'published', ARRAY[{ingredient}], ARRAY[]::text[], "
                    f"(SELECT array_agg(0.1)::vector(768) FROM generate_series(1, 768)), now())"
                )
                index += 1

    body = [header + ",\n".join(rows) + ";", "", "SELECT tests.authenticate_as_anon();", ""]

    body += [
        "-- The control is reachable before anything is excluded, so every assertion below is about",
        "-- the exclusion rather than about a Meal that was never visible.",
        "SELECT is(",
        f"  (SELECT count(*)::int FROM public.search_meals((SELECT v FROM probe), NULL, NULL)",
        f"   WHERE id = {control_id}),",
        "  1,",
        "  'the control Meal is on offer — the baseline the rest of this sweep rests on'",
        ");",
        "",
    ]

    for eid, forms in exclusions:
        terms = sql_text_array(forms)
        ids = ", ".join(ids_by_exclusion[eid])
        body += [
            f"-- {eid}: every spelling of every form, excluded.",
            "SELECT is(",
            f"  (SELECT count(*)::int FROM public.search_meals((SELECT v FROM probe), {terms}, NULL)",
            f"   WHERE id IN ({ids})),",
            "  0,",
            f"  'SC-005: no Meal containing {eid} appears when {eid} is excluded — "
            f"{len(ids_by_exclusion[eid])} spelling(s) checked'",
            ");",
            "",
            "SELECT is(",
            f"  (SELECT count(*)::int FROM public.search_meals((SELECT v FROM probe), {terms}, NULL)",
            f"   WHERE id = {control_id}),",
            "  1,",
            f"  'excluding {eid} does not remove a Meal that has none of it — an exclusion is not a "
            f"licence to show nothing'",
            ");",
            "",
        ]

    body += [
        "-- Nothing on the control matches any exclusion. Asserted rather than assumed: if a form is",
        "-- ever added that reaches rice, every control assertion above would fail together and the",
        "-- cause would not be obvious from any of them.",
        "SELECT is(",
        "  (SELECT count(*)::int FROM public.search_meals((SELECT v FROM probe), "
        + sql_text_array(sorted({f for _, forms in exclusions for f in forms}))
        + ", NULL)",
        f"   WHERE id = {control_id}),",
        "  1,",
        "  'the control survives EVERY form in the vocabulary at once'",
        ");",
        "",
        "SELECT * FROM finish();",
        "ROLLBACK;",
    ]

    return "\n".join(body) + "\n"


def main() -> int:
    dart = strip_comments(SOURCE.read_text(encoding="utf-8"))
    all_match = ALL_BLOCK.search(dart)
    if not all_match:
        raise SystemExit(
            f"{SOURCE} no longer has the shape this generator reads. Fix the generator rather than "
            f"hand-writing {TARGET} — a hand-written sweep is a sweep of what somebody remembered."
        )

    exclusions = [(eid, QUOTED.findall(forms)) for eid, forms in ENTRY.findall(all_match.group(1))]
    if not exclusions:
        raise SystemExit("parsed an empty vocabulary — refusing to write a sweep of nothing")

    rendered = render(exclusions)

    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"   {TARGET} has not been generated yet")
            return 1
        if TARGET.read_text(encoding="utf-8") != rendered:
            print(f"   {TARGET} is stale — run: python3 {__file__}")
            return 1
        print(f"   exclusion sweep matches ({len(exclusions)} exclusion(s))")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}: {len(exclusions)} exclusions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
